mystr="arpit is a good boy"
"""
print(len(mystr))

print(mystr[0:45])
print(mystr[0:45:3])
print(mystr[0:65:2])
print(mystr[:45])
print(mystr[0:])
print(mystr[0::14])
print(mystr[:])
print(mystr[::])
print(mystr[::4])
print(mystr[0:19])
print(mystr[::9])
print(len(mystr))
print(mystr[::888])

#print(mystr[-7:-1:2])
#print(mystr[::-1])
#print(mystr[::-2])
print(type(mystr))
print(mystr)
print(mystr.isalnum())
print(mystr.endswith("boy"))
print(mystr.count("a"))
print(mystr.capitalize())
print(mystr.find("is"))
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("is","are"))
"""